{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Database connection created successfully.\n",
      "{\n",
      "  \"id\": \"a7146dba-ad91-4994-812e-eff9e1d2f111\",\n",
      "  \"alias\": \"service_instances\",\n",
      "  \"dialect\": \"postgresql\",\n",
      "  \"connection_uri\": \"gAAAAABm4GBzhdyQ0G0VfVbTbRiBWnobnD4vzgu6_7m8UBqWwGkTIo4bfnkuvpc1AJyxg0uTqZniYILslkmcJHL2m1TspgNpD9UdZQOEYv8bmy_ww59W6wIwKoRN7z5eB85iX9jToXGevZuqPZ3lR_cKAYXtPq_NZg==\",\n",
      "  \"schemas\": [\n",
      "    \"public\"\n",
      "  ],\n",
      "  \"metadata\": {},\n",
      "  \"created_at\": \"2024-09-10T22:06:27.153462\"\n",
      "}\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "import json\n",
    "\n",
    "# Define the base URL\n",
    "base_url = \"http://localhost:8000\"\n",
    "\n",
    "# Define the endpoint for creating a database connection\n",
    "endpoint = \"/api/v1/database-connections\"\n",
    "\n",
    "# Define the payload for the POST request\n",
    "payload = {\n",
    "    \"alias\": \"service_instances\",\n",
    "    \"connection_uri\": \"postgresql://myuser:mypassword@localhost:15432/mydatabase\",\n",
    "    \"schemas\": [\n",
    "        \"public\"\n",
    "    ],\n",
    "    \"metadata\": {}\n",
    "}\n",
    "\n",
    "# Send the POST request to create a database connection\n",
    "response = requests.post(f\"{base_url}{endpoint}\", json=payload)\n",
    "\n",
    "# Check the response status\n",
    "if response.status_code == 201:\n",
    "    print(\"Database connection created successfully.\")\n",
    "    print(json.dumps(response.json(), indent=2))  # Print the response data\n",
    "else:\n",
    "    print(f\"Failed to create database connection. Status Code: {response.status_code}\")\n",
    "    print(response.text)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Database connection created successfully.\n",
      "{\n",
      "  \"id\": \"1affbce9-b94b-4e0c-a91d-0f88769d4983\",\n",
      "  \"alias\": \"service_instances\",\n",
      "  \"dialect\": \"postgresql\",\n",
      "  \"connection_uri\": \"gAAAAABm4GFiIVmoyQaOW4M5tBhSnX0u3B28t2yyMFdsD2FubHFrV29eW8yTuXDgY0-3SphMLtqe9ukQ5nZWWnMf2Z9bnbuoV8Vmdt6n-qa591u2dEKEEwWPURrAx-vCAZwy81tpxG1FTbTqbAaV-7TWElUpSLgxPA==\",\n",
      "  \"schemas\": [\n",
      "    \"public\"\n",
      "  ],\n",
      "  \"metadata\": {},\n",
      "  \"created_at\": \"2024-09-10T22:10:26.603773\"\n",
      "}\n"
     ]
    }
   ],
   "source": [
    "# Send the POST request to create a database connection\n",
    "response = requests.post(f\"{base_url}{endpoint}\", json=payload)\n",
    "\n",
    "# Check the response status\n",
    "if response.status_code == 201:\n",
    "    print(\"Database connection created successfully.\")\n",
    "    print(json.dumps(response.json(), indent=2))  # Print the response data\n",
    "else:\n",
    "    print(f\"Failed to create database connection. Status Code: {response.status_code}\")\n",
    "    print(response.text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[{'id': '1affbce9-b94b-4e0c-a91d-0f88769d4983', 'alias': 'service_instances', 'dialect': 'postgresql', 'connection_uri': 'gAAAAABm4GFiIVmoyQaOW4M5tBhSnX0u3B28t2yyMFdsD2FubHFrV29eW8yTuXDgY0-3SphMLtqe9ukQ5nZWWnMf2Z9bnbuoV8Vmdt6n-qa591u2dEKEEwWPURrAx-vCAZwy81tpxG1FTbTqbAaV-7TWElUpSLgxPA==', 'schemas': ['public'], 'metadata': {}, 'created_at': '2024-09-10T22:10:26.603773'}, {'id': 'a7146dba-ad91-4994-812e-eff9e1d2f111', 'alias': 'service_instances', 'dialect': 'postgresql', 'connection_uri': 'gAAAAABm4GBzhdyQ0G0VfVbTbRiBWnobnD4vzgu6_7m8UBqWwGkTIo4bfnkuvpc1AJyxg0uTqZniYILslkmcJHL2m1TspgNpD9UdZQOEYv8bmy_ww59W6wIwKoRN7z5eB85iX9jToXGevZuqPZ3lR_cKAYXtPq_NZg==', 'schemas': ['public'], 'metadata': {}, 'created_at': '2024-09-10T22:06:27.153462'}, {'id': '23e59cd2-be00-4b87-b799-d781070c8a57', 'alias': 'postgresdvd', 'dialect': 'postgresql', 'connection_uri': 'gAAAAABm0CiyWCdSD1clIfSdfzKgE4kh-3-30Wp3frONblMCJrKgVp2tVdq9qqa_fqWuAo6v5NJtkjY7lUh85brQVySvBjzO-Xwgeo3l-4NPghb-yTDO4Tm4mBwXc2qs1mvaMLTNjl0KEiP_uIK7sJzFahvgg731QhbzShdQWjgxVxzezyyEdJ0=', 'schemas': ['public'], 'metadata': {}, 'created_at': '2024-08-29T14:52:17.971425'}]\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "\n",
    "response = requests.get('http://localhost:8000/api/v1/database-connections')\n",
    "if response.status_code == 200:\n",
    "    connections = response.json()\n",
    "    print(connections)\n",
    "else:\n",
    "    print(f\"Error: {response.status_code}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'1affbce9-b94b-4e0c-a91d-0f88769d4983'"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "db_id = connections[0]['id']\n",
    "db_id"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "200\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "[{'id': '370262d3-5cbb-4bcf-bdb0-ac8f08e44b74',\n",
       "  'db_connection_id': '1affbce9-b94b-4e0c-a91d-0f88769d4983',\n",
       "  'db_schema': 'public',\n",
       "  'table_name': 'service_instances',\n",
       "  'columns': [],\n",
       "  'examples': [],\n",
       "  'table_description': None,\n",
       "  'table_embedding': None,\n",
       "  'table_schema': None,\n",
       "  'sync_status': 'NOT_SCANNED',\n",
       "  'last_sync': None,\n",
       "  'error_message': None,\n",
       "  'metadata': None,\n",
       "  'created_at': '2024-09-10T22:10:26.843621'}]"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import requests\n",
    "\n",
    "url = \"http://localhost:8000/api/v1/table-descriptions\"\n",
    "params = {}\n",
    "params['db_connection_id'] = db_id\n",
    "\n",
    "response = requests.get(url, params=params)\n",
    "\n",
    "print(response.status_code)\n",
    "response.json()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'370262d3-5cbb-4bcf-bdb0-ac8f08e44b74'"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "table_id = response.json()[0]['id']\n",
    "table_id"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "ename": "Exception",
     "evalue": "Error: 500, Traceback (most recent call last):\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    await self.app(scope, receive, _send)\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n    raise exc\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\routing.py\", line 715, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\routing.py\", line 735, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n    raise exc\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\fastapi\\routing.py\", line 297, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\fastapi\\routing.py\", line 212, in run_endpoint_function\n    return await run_in_threadpool(dependant.call, **values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\concurrency.py\", line 39, in run_in_threadpool\n    return await anyio.to_thread.run_sync(func, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\anyio\\to_thread.py\", line 56, in run_sync\n    return await get_async_backend().run_sync_in_worker_thread(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 2177, in run_sync_in_worker_thread\n    return await future\n           ^^^^^^^^^^^^\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 859, in run\n    result = context.run(func, *args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\edisu\\Documents\\GitHub\\KAI\\app\\api\\__init__.py\", line 439, in refresh_table_description\n    table_descriptions = self.table_description_service.refresh_table_description(\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\edisu\\Documents\\GitHub\\KAI\\app\\modules\\table_description\\services\\__init__.py\", line 73, in refresh_table_description\n    database_connection_service = DatabaseConnectionService(self.storage)\n                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: DatabaseConnectionService.__init__() missing 1 required positional argument: 'storage'\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mException\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[25], line 18\u001b[0m\n\u001b[0;32m     15\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mError: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mresponse\u001b[38;5;241m.\u001b[39mstatus_code\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m, \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mresponse\u001b[38;5;241m.\u001b[39mtext\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m     17\u001b[0m \u001b[38;5;66;03m# Example usage\u001b[39;00m\n\u001b[1;32m---> 18\u001b[0m result \u001b[38;5;241m=\u001b[39m \u001b[43mrefresh_table_descriptions\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdb_id\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     19\u001b[0m \u001b[38;5;28mprint\u001b[39m(result)\n",
      "Cell \u001b[1;32mIn[25], line 15\u001b[0m, in \u001b[0;36mrefresh_table_descriptions\u001b[1;34m(db_connection_id)\u001b[0m\n\u001b[0;32m     13\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m response\u001b[38;5;241m.\u001b[39mjson()  \u001b[38;5;66;03m# or handle the response as needed\u001b[39;00m\n\u001b[0;32m     14\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m---> 15\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mError: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mresponse\u001b[38;5;241m.\u001b[39mstatus_code\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m, \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mresponse\u001b[38;5;241m.\u001b[39mtext\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[1;31mException\u001b[0m: Error: 500, Traceback (most recent call last):\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\middleware\\errors.py\", line 165, in __call__\n    await self.app(scope, receive, _send)\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\middleware\\exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n    raise exc\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\routing.py\", line 715, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\routing.py\", line 735, in app\n    await route.handle(scope, receive, send)\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 62, in wrapped_app\n    raise exc\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\_exception_handler.py\", line 51, in wrapped_app\n    await app(scope, receive, sender)\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\fastapi\\routing.py\", line 297, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\fastapi\\routing.py\", line 212, in run_endpoint_function\n    return await run_in_threadpool(dependant.call, **values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\starlette\\concurrency.py\", line 39, in run_in_threadpool\n    return await anyio.to_thread.run_sync(func, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\anyio\\to_thread.py\", line 56, in run_sync\n    return await get_async_backend().run_sync_in_worker_thread(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 2177, in run_sync_in_worker_thread\n    return await future\n           ^^^^^^^^^^^^\n  File \"C:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 859, in run\n    result = context.run(func, *args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\edisu\\Documents\\GitHub\\KAI\\app\\api\\__init__.py\", line 439, in refresh_table_description\n    table_descriptions = self.table_description_service.refresh_table_description(\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\edisu\\Documents\\GitHub\\KAI\\app\\modules\\table_description\\services\\__init__.py\", line 73, in refresh_table_description\n    database_connection_service = DatabaseConnectionService(self.storage)\n                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: DatabaseConnectionService.__init__() missing 1 required positional argument: 'storage'\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "\n",
    "def refresh_table_descriptions(db_connection_id):\n",
    "    url = \"http://localhost:8000/api/v1/table-descriptions/refresh\"\n",
    "    params = {}\n",
    "    params['database_connection_id'] = db_connection_id\n",
    "    \n",
    "    # Send a POST request\n",
    "    response = requests.post(url, params=params)\n",
    "\n",
    "    # Check the response status and return accordingly\n",
    "    if response.status_code == 200:\n",
    "        return response.json()  # or handle the response as needed\n",
    "    else:\n",
    "        raise Exception(f\"Error: {response.status_code}, {response.text}\")\n",
    "\n",
    "# Example usage\n",
    "result = refresh_table_descriptions(db_id)\n",
    "print(result)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Status Code: 201\n",
      "Response JSON: [{'id': '370262d3-5cbb-4bcf-bdb0-ac8f08e44b74', 'db_connection_id': '1affbce9-b94b-4e0c-a91d-0f88769d4983', 'db_schema': 'public', 'table_name': 'service_instances', 'columns': [], 'examples': [], 'table_description': None, 'table_embedding': None, 'table_schema': None, 'sync_status': 'SYNCHRONIZING', 'last_sync': None, 'error_message': None, 'metadata': {}, 'created_at': '2024-09-11T10:04:31.907107'}]\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "\n",
    "# Define your request body\n",
    "request_body = {\n",
    "    \"table_description_ids\": [table_id],\n",
    "    \"metadata\": {}\n",
    "}\n",
    "\n",
    "# Send the POST request\n",
    "response = requests.post(\"http://localhost:8000/api/v1/table-descriptions/sync-schemas\", json=request_body)\n",
    "\n",
    "# Print the response\n",
    "print(\"Status Code:\", response.status_code)\n",
    "print(\"Response JSON:\", response.json())\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Status Code: 201\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'id': 'e90d0f38-3e8e-4d06-9def-c2d318c200a7',\n",
       " 'metadata': {},\n",
       " 'created_at': '2024-09-11T10:38:14.555395',\n",
       " 'text': 'What is the average revenue loss due to churn in 2023?',\n",
       " 'db_connection_id': '1affbce9-b94b-4e0c-a91d-0f88769d4983',\n",
       " 'schemas': ['public']}"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import requests\n",
    "\n",
    "# Define your request body for creating a prompt\n",
    "request_body = {\n",
    "    \"text\": \"What is the average revenue loss due to churn in 2023?\",   # Replace with the actual prompt text\n",
    "    \"db_connection_id\": db_id,  # Replace with your actual DB connection ID\n",
    "    \"schemas\": [\"public\"],  # Add your actual schemas\n",
    "    \"context\": [{}],  # Replace with actual context objects if needed\n",
    "    \"metadata\": {}    # Add any additional metadata if needed\n",
    "}\n",
    "\n",
    "# Send the POST request to create a prompt\n",
    "response = requests.post(\"http://localhost:8000/api/v1/prompts\", json=request_body)\n",
    "\n",
    "# Print the response\n",
    "print(\"Status Code:\", response.status_code)\n",
    "response.json()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'e90d0f38-3e8e-4d06-9def-c2d318c200a7'"
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "prompt_id = response.json()['id']\n",
    "prompt_id"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "SQL Generation Status Code: 500\n"
     ]
    },
    {
     "ename": "JSONDecodeError",
     "evalue": "Expecting value: line 1 column 1 (char 0)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mJSONDecodeError\u001b[0m                           Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\requests\\models.py:974\u001b[0m, in \u001b[0;36mResponse.json\u001b[1;34m(self, **kwargs)\u001b[0m\n\u001b[0;32m    973\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 974\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mcomplexjson\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mloads\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mtext\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    975\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m JSONDecodeError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m    976\u001b[0m     \u001b[38;5;66;03m# Catch JSON-related errors and raise as requests.JSONDecodeError\u001b[39;00m\n\u001b[0;32m    977\u001b[0m     \u001b[38;5;66;03m# This aliases json.JSONDecodeError and simplejson.JSONDecodeError\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\json\\__init__.py:346\u001b[0m, in \u001b[0;36mloads\u001b[1;34m(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)\u001b[0m\n\u001b[0;32m    343\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m (\u001b[38;5;28mcls\u001b[39m \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;129;01mand\u001b[39;00m object_hook \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;129;01mand\u001b[39;00m\n\u001b[0;32m    344\u001b[0m         parse_int \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;129;01mand\u001b[39;00m parse_float \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;129;01mand\u001b[39;00m\n\u001b[0;32m    345\u001b[0m         parse_constant \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;129;01mand\u001b[39;00m object_pairs_hook \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m kw):\n\u001b[1;32m--> 346\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43m_default_decoder\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mdecode\u001b[49m\u001b[43m(\u001b[49m\u001b[43ms\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    347\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mcls\u001b[39m \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "File \u001b[1;32mc:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\json\\decoder.py:337\u001b[0m, in \u001b[0;36mJSONDecoder.decode\u001b[1;34m(self, s, _w)\u001b[0m\n\u001b[0;32m    333\u001b[0m \u001b[38;5;250m\u001b[39m\u001b[38;5;124;03m\"\"\"Return the Python representation of ``s`` (a ``str`` instance\u001b[39;00m\n\u001b[0;32m    334\u001b[0m \u001b[38;5;124;03mcontaining a JSON document).\u001b[39;00m\n\u001b[0;32m    335\u001b[0m \n\u001b[0;32m    336\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m--> 337\u001b[0m obj, end \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mraw_decode\u001b[49m\u001b[43m(\u001b[49m\u001b[43ms\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43midx\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m_w\u001b[49m\u001b[43m(\u001b[49m\u001b[43ms\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m0\u001b[39;49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mend\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    338\u001b[0m end \u001b[38;5;241m=\u001b[39m _w(s, end)\u001b[38;5;241m.\u001b[39mend()\n",
      "File \u001b[1;32mc:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\json\\decoder.py:355\u001b[0m, in \u001b[0;36mJSONDecoder.raw_decode\u001b[1;34m(self, s, idx)\u001b[0m\n\u001b[0;32m    354\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mStopIteration\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[1;32m--> 355\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m JSONDecodeError(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mExpecting value\u001b[39m\u001b[38;5;124m\"\u001b[39m, s, err\u001b[38;5;241m.\u001b[39mvalue) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m    356\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m obj, end\n",
      "\u001b[1;31mJSONDecodeError\u001b[0m: Expecting value: line 1 column 1 (char 0)",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mJSONDecodeError\u001b[0m                           Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[36], line 20\u001b[0m\n\u001b[0;32m     18\u001b[0m \u001b[38;5;66;03m# # Print the response from the SQL generation request\u001b[39;00m\n\u001b[0;32m     19\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mSQL Generation Status Code:\u001b[39m\u001b[38;5;124m\"\u001b[39m, sql_generation_response\u001b[38;5;241m.\u001b[39mstatus_code)\n\u001b[1;32m---> 20\u001b[0m \u001b[43msql_generation_response\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mjson\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\Users\\edisu\\anaconda3\\envs\\KAI-dev\\Lib\\site-packages\\requests\\models.py:978\u001b[0m, in \u001b[0;36mResponse.json\u001b[1;34m(self, **kwargs)\u001b[0m\n\u001b[0;32m    974\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m complexjson\u001b[38;5;241m.\u001b[39mloads(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mtext, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[0;32m    975\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m JSONDecodeError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m    976\u001b[0m     \u001b[38;5;66;03m# Catch JSON-related errors and raise as requests.JSONDecodeError\u001b[39;00m\n\u001b[0;32m    977\u001b[0m     \u001b[38;5;66;03m# This aliases json.JSONDecodeError and simplejson.JSONDecodeError\u001b[39;00m\n\u001b[1;32m--> 978\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m RequestsJSONDecodeError(e\u001b[38;5;241m.\u001b[39mmsg, e\u001b[38;5;241m.\u001b[39mdoc, e\u001b[38;5;241m.\u001b[39mpos)\n",
      "\u001b[1;31mJSONDecodeError\u001b[0m: Expecting value: line 1 column 1 (char 0)"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "\n",
    "# Create the request body for SQL generation\n",
    "sql_generation_request_body = {\n",
    "    \"llm_config\": {\n",
    "        \"llm_name\": \"gpt-4o-mini\"\n",
    "    },\n",
    "    \"evaluate\": True,\n",
    "    \"metadata\": {}      # Add any additional metadata if needed\n",
    "}\n",
    "\n",
    "# Send the POST request to create SQL generation\n",
    "sql_generation_response = requests.post(\n",
    "    f\"http://localhost:8000/api/v1/prompts/{prompt_id}/sql-generations\", \n",
    "    json=sql_generation_request_body\n",
    ")\n",
    "\n",
    "# # Print the response from the SQL generation request\n",
    "print(\"SQL Generation Status Code:\", sql_generation_response.status_code)\n",
    "sql_generation_response.json()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Response [500]>"
      ]
     },
     "execution_count": 32,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "sql_generation_response"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "KAI-dev",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
